version: '3.7'

networks:
  rajce-proxy.network:
    driver: bridge

services:
  php:
    build: ./docker/php
    restart: always
    tty: true
    container_name: rajce-proxy.php
    depends_on:
      - redis
    networks:
      - rajce-proxy.network
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/app.dev
    environment:
      - NETTE_DEBUG

  apache:
    build: ./docker/apache
    restart: always
    container_name: rajce-proxy.apache
    networks:
      - rajce-proxy.network
    depends_on:
      - php
      - redis
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/app.dev

  redis:
    container_name: rajce-proxy.redis
    image: bitnami/redis:latest
    hostname: redis
    restart: always
    networks:
      - rajce-proxy.network
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis:/bitnami/redis/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  redis-commander:
    container_name: rajce-proxy.redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    depends_on:
      - redis
    networks:
      - rajce-proxy.network
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
